# Generated by Django 2.2.6 on 2019-11-21 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bedroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total')),
                ('start', models.DateField(default=django.utils.timezone.now, verbose_name='Start')),
                ('finish', models.DateField(default=django.utils.timezone.now, verbose_name='Finish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bedroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bedroom.Bedroom', verbose_name='Bedroom')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookigns',
                'ordering': ['-updated_at'],
            },
        ),
    ]
