# Generated by Django 2.2.6 on 2020-01-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
