# Generated by Django 2.2.6 on 2019-11-21 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('bathroom', models.IntegerField(verbose_name='Bathroom')),
                ('bed', models.IntegerField(verbose_name='Bed')),
                ('daily', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Daily Price')),
            ],
        ),
        migrations.CreateModel(
            name='BedroomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='bedroom_images', verbose_name='Bedroom Images')),
                ('bedroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedroom.Bedroom', verbose_name='Bedroom')),
            ],
        ),
    ]
