# Generated by Django 2.2.6 on 2020-06-12 02:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bedroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedroom',
            options={'ordering': ['floor', 'number'], 'verbose_name': 'Bedroom', 'verbose_name_plural': 'Bedrooms'},
        ),
        migrations.AlterModelOptions(
            name='bedroomimage',
            options={'ordering': ['bedroom__floor', 'bedroom__number'], 'verbose_name': 'Bedroom Image', 'verbose_name_plural': 'Bedroom Images'},
        ),
        migrations.AddField(
            model_name='bedroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedroom',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is Available'),
        ),
        migrations.AddField(
            model_name='bedroom',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AddField(
            model_name='bedroomimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedroomimage',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='daily',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price per day'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='number',
            field=models.IntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='bedroomimage',
            name='bedroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='bedroom_photos', to='bedroom.Bedroom', verbose_name='Bedroom'),
        ),
    ]
