# Generated by Django 2.2.6 on 2019-12-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bedroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroomimage',
            name='bedroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bedroom.Bedroom', verbose_name='Bedroom'),
        ),
    ]
